# This is a basic workflow to help you get started with Actions

name: Execute Sample Script

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  Development:
    name: "Run Shell script-dev"
    runs-on: ubuntu-latest
    environment: dev
    
    defaults:
     run:
       shell: bash
       working-directory: "Test"
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: subba1
    - name: run script
      run:  |
            echo ${{ secrets.platform }}
            bash ./sample.sh ${{ secrets.platform }}
  Test:
    name: "Run Shell script-test"
    runs-on: ubuntu-latest
    environment: Test
    
    defaults:
     run:
       shell: bash
       working-directory: "Test"
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: subba1
    - name: run script
      run:  |
            echo ${{ secrets.platform }}
            bash ./sample.sh ${{ secrets.platform }}
